/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/El3kVbMDpDO
 */
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import Link from "next/link"

export function Component() {
  return (
    <section className="container mx-auto px-4 md:px-6 py-6 grid md:grid-cols-[1fr_3fr] gap-6 items-start">
      <aside className="flex flex-col gap-4">
        <h2 className="text-lg font-bold">Filters</h2>
        <Accordion className="w-full" collapsible type="single">
          <AccordionItem value="category">
            <AccordionTrigger className="text-base">Category</AccordionTrigger>
            <AccordionContent>
              <div className="grid gap-2">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="category-1" />
                  Category 1{"\n                          "}
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="category-2" />
                  Category 2{"\n                          "}
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="category-3" />
                  Category 3{"\n                          "}
                </Label>
              </div>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="price">
            <AccordionTrigger className="text-base">Price</AccordionTrigger>
            <AccordionContent>
              <div className="grid gap-2">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="price-1" />
                  $0 - $50{"\n                          "}
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="price-2" />
                  $51 - $100{"\n                          "}
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="price-3" />
                  $101 - $150{"\n                          "}
                </Label>
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </aside>
      <main className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-6 md:gap-8">
        <div className="relative group">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View Product 1</span>
          </Link>
          <img
            alt="Product 1"
            className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
            height="200"
            src="/placeholder.svg"
            width="200"
          />
          <div className="flex-1 py-4">
            <h3 className="font-semibold tracking-tight">Product 1</h3>
            <h4 className="font-semibold">$19.99</h4>
          </div>
        </div>
        <div className="relative group">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View Product 2</span>
          </Link>
          <img
            alt="Product 2"
            className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
            height="200"
            src="/placeholder.svg"
            width="200"
          />
          <div className="flex-1 py-4">
            <h3 className="font-semibold tracking-tight">Product 2</h3>
            <h4 className="font-semibold">$29.99</h4>
          </div>
        </div>
        <div className="relative group">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View Product 3</span>
          </Link>
          <img
            alt="Product 3"
            className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
            height="200"
            src="/placeholder.svg"
            width="200"
          />
          <div className="flex-1 py-4">
            <h3 className="font-semibold tracking-tight">Product 3</h3>
            <h4 className="font-semibold">$39.99</h4>
          </div>
        </div>
        <div className="relative group">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View Product 4</span>
          </Link>
          <img
            alt="Product 4"
            className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
            height="200"
            src="/placeholder.svg"
            width="200"
          />
          <div className="flex-1 py-4">
            <h3 className="font-semibold tracking-tight">Product 4</h3>
            <h4 className="font-semibold">$49.99</h4>
          </div>
        </div>
        <div className="relative group">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View Product 5</span>
          </Link>
          <img
            alt="Product 5"
            className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
            height="200"
            src="/placeholder.svg"
            width="200"
          />
          <div className="flex-1 py-4">
            <h3 className="font-semibold tracking-tight">Product 5</h3>
            <h4 className="font-semibold">$59.99</h4>
          </div>
        </div>
      </main>
    </section>
  )
}
